const CONFIG = {
  canvas: { width: 960, height: 600 },
  tile: 40,
  start: { gold: 200, lives: 20 },

  path: [
    { x: -20,  y: 100 },
    { x: 260,  y: 100 },
    { x: 260,  y: 260 },
    { x: 620,  y: 260 },
    { x: 620,  y: 100 },
    { x: 820,  y: 100 },
    { x: 820,  y: 460 },
    { x: 140,  y: 460 },
    { x: 140,  y: 540 },
    { x: 980,  y: 540 },
  ],
  pathWidth: 36,

  towers: {
    archer: {
      name: '箭塔',
      cost: 50,
      range: 140,
      damage: 8,
      fireRate: 0.45,
      color: '#06d6a0',
      accent: '#0a7a5c',
      bulletSpeed: 520,
      splash: 0,
      slow: 0,
    },
    cannon: {
      name: '炮塔',
      cost: 120,
      range: 110,
      damage: 30,
      fireRate: 1.4,
      color: '#ef476f',
      accent: '#8a1f38',
      bulletSpeed: 340,
      splash: 55,
      slow: 0,
    },
    frost: {
      name: '冰塔',
      cost: 90,
      range: 120,
      damage: 4,
      fireRate: 0.6,
      color: '#118ab2',
      accent: '#073b4c',
      bulletSpeed: 460,
      splash: 30,
      slow: 0.45,
      slowDuration: 1.8,
    },
  },

  enemies: {
    grunt: {
      name: '小兵',
      hp: 60,
      speed: 70,
      gold: 8,
      score: 10,
      color: '#ffd166',
      radius: 11,
    },
    runner: {
      name: '疾行者',
      hp: 35,
      speed: 140,
      gold: 10,
      score: 15,
      color: '#06d6a0',
      radius: 9,
    },
    tank: {
      name: '坦克',
      hp: 320,
      speed: 42,
      gold: 30,
      score: 50,
      color: '#6a4c93',
      radius: 15,
    },
    boss: {
      name: 'BOSS',
      hp: 1800,
      speed: 32,
      gold: 200,
      score: 500,
      color: '#ef476f',
      radius: 22,
    },
  },

  waves: [
    { enemies: [ { type: 'grunt', count: 6, delay: 0.9 } ] },
    { enemies: [ { type: 'grunt', count: 10, delay: 0.7 } ] },
    { enemies: [ { type: 'grunt', count: 8, delay: 0.7 }, { type: 'runner', count: 4, delay: 0.5 } ] },
    { enemies: [ { type: 'runner', count: 12, delay: 0.45 } ] },
    { enemies: [ { type: 'grunt', count: 10, delay: 0.6 }, { type: 'tank', count: 2, delay: 1.8 } ] },
    { enemies: [ { type: 'tank', count: 5, delay: 1.4 }, { type: 'runner', count: 8, delay: 0.5 } ] },
    { enemies: [ { type: 'grunt', count: 15, delay: 0.5 }, { type: 'tank', count: 4, delay: 1.4 }, { type: 'runner', count: 6, delay: 0.5 } ] },
    { enemies: [ { type: 'runner', count: 20, delay: 0.35 } ] },
    { enemies: [ { type: 'tank', count: 10, delay: 1.1 } ] },
    { enemies: [ { type: 'grunt', count: 12, delay: 0.5 }, { type: 'runner', count: 10, delay: 0.4 }, { type: 'tank', count: 6, delay: 1.2 }, { type: 'boss', count: 1, delay: 2 } ] },
  ],
};
